Feature/navbar
pablistem/Pizzeria-Frontend pull request #16
Opened 2023-12-15 00:01 UTC by JoseI11

# Summary

- I made the component navbar to navigate with its responsive aspect 
- I check the navbar with a cypress test
...

# Detail

If needed, a detailed explanation of what the pr is about.

# Evidence

![Vite-React-TS-—-Mozilla-Firefox-2023-12-13-22-42-39](https://github.com/pablistem/Pizzeria-Frontend/assets/100376407/9d4ec3ba-84e8-4453-a03c-388b4f252189)

# Reference.

![tarea jira navbar](https://github.com/pablistem/Pizzeria-Frontend/assets/100376407/22367f4b-211a-4063-89ad-ea7bd5826caa)

2023-12-15 21:45 UTC, Fludeo requested changes

2023-12-15 21:45 UTC, Fludeo commented on cypress/screenshots/components/navbar.cy.ts/Navbar test -- Should show the navbar (failed).png
We should not send all these pngs. I will change the config so Cypress does not produce these pngs.

2023-12-15 21:45 UTC, Fludeo commented on src/App.tsx
> +        <Route path="/Home" element={<Home />} />{' '}
pls change "Home" to "home" and keep the lowercase at the beginning of every route. Use kebab case for multiple words.

2023-12-18 14:05 UTC, JoseI11 commented on src/App.tsx
> +        <Route path="/Home" element={<Home />} />{' '}
Done

2023-12-18 14:33 UTC, JoseI11 commented on cypress/screenshots/components/navbar.cy.ts/Navbar test -- Should show the navbar (failed).png
Done, I add the folder screenshots to gitignore

2023-12-19 00:37 UTC, Fludeo approved these changes
Great.

2023-12-19 00:37 UTC, merged